<?php

  $schedule_fields_list = array(
    'timeZone' => array(
      array("value" => "", "label" => "Please Select a Time Zone"),
      array("value" => "-1200", "label" => "(UTC-12:00) UTC/GMT-12:00"),
      array("value" => "Pacific/Niue", "label" => "(UTC-11:00) Pacific - Niue"),
      array("value" => "Pacific/Pago_Pago", "label" => "(UTC-11:00) Pacific - Pago Pago"),
      array("value" => "-1100", "label" => "(UTC-11:00) UTC/GMT-11:00"),
      array("value" => "Pacific/Midway", "label" => "(UTC-11:00) Pacific - Midway"),
      array("value" => "-1000", "label" => "(UTC-10:00) UTC/GMT-10:00"),
      array("value" => "Pacific/Tahiti", "label" => "(UTC-10:00) Pacific - Tahiti"),
      array("value" => "Pacific/Rarotonga", "label" => "(UTC-10:00) Pacific - Rarotonga"),
      array("value" => "Pacific/Honolulu", "label" => "(UTC-10:00) Pacific - Honolulu"),
      array("value" => "Pacific/Marquesas", "label" => "(UTC-09:30) Pacific - Marquesas"),
      array("value" => "-0930", "label" => "(UTC-09:30) UTC/GMT-09:30"),
      array("value" => "America/Adak", "label" => "(UTC-09:00) America - Adak"),
      array("value" => "-0900", "label" => "(UTC-09:00) UTC/GMT-09:00"),
      array("value" => "Pacific/Gambier", "label" => "(UTC-09:00) Pacific - Gambier"),
      array("value" => "-0800", "label" => "(UTC-08:00) UTC/GMT-08:00"),
      array("value" => "America/Anchorage", "label" => "(UTC-08:00) America - Anchorage"),
      array("value" => "America/Sitka", "label" => "(UTC-08:00) America - Sitka"),
      array("value" => "Pacific/Pitcairn", "label" => "(UTC-08:00) Pacific - Pitcairn"),
      array("value" => "America/Juneau", "label" => "(UTC-08:00) America - Juneau"),
      array("value" => "America/Metlakatla", "label" => "(UTC-08:00) America - Metlakatla"),
      array("value" => "America/Nome", "label" => "(UTC-08:00) America - Nome"),
      array("value" => "America/Yakutat", "label" => "(UTC-08:00) America - Yakutat"),
      array("value" => "America/Dawson", "label" => "(UTC-07:00) America - Dawson"),
      array("value" => "America/Dawson_Creek", "label" => "(UTC-07:00) America - Dawson Creek"),
      array("value" => "America/Fort_Nelson", "label" => "(UTC-07:00) America - Fort Nelson"),
      array("value" => "America/Hermosillo", "label" => "(UTC-07:00) America - Hermosillo"),
      array("value" => "America/Los_Angeles", "label" => "(UTC-07:00) America - Los Angeles"),
      array("value" => "America/Phoenix", "label" => "(UTC-07:00) America - Phoenix"),
      array("value" => "America/Tijuana", "label" => "(UTC-07:00) America - Tijuana"),
      array("value" => "America/Vancouver", "label" => "(UTC-07:00) America - Vancouver"),
      array("value" => "America/Whitehorse", "label" => "(UTC-07:00) America - Whitehorse"),
      array("value" => "America/Creston", "label" => "(UTC-07:00) America - Creston"),
      array("value" => "-0700", "label" => "(UTC-07:00) UTC/GMT-07:00"),
      array("value" => "America/Mazatlan", "label" => "(UTC-06:00) America - Mazatlan"),
      array("value" => "America/Tegucigalpa", "label" => "(UTC-06:00) America - Tegucigalpa"),
      array("value" => "America/Belize", "label" => "(UTC-06:00) America - Belize"),
      array("value" => "America/Boise", "label" => "(UTC-06:00) America - Boise"),
      array("value" => "America/Cambridge_Bay", "label" => "(UTC-06:00) America - Cambridge Bay"),
      array("value" => "America/Chihuahua", "label" => "(UTC-06:00) America - Chihuahua"),
      array("value" => "America/Costa_Rica", "label" => "(UTC-06:00) America - Costa Rica"),
      array("value" => "Pacific/Galapagos", "label" => "(UTC-06:00) Pacific - Galapagos"),
      array("value" => "Pacific/Easter", "label" => "(UTC-06:00) Pacific - Easter"),
      array("value" => "America/Regina", "label" => "(UTC-06:00) America - Regina"),
      array("value" => "America/Denver", "label" => "(UTC-06:00) America - Denver"),
      array("value" => "America/Edmonton", "label" => "(UTC-06:00) America - Edmonton"),
      array("value" => "America/Ojinaga", "label" => "(UTC-06:00) America - Ojinaga"),
      array("value" => "America/Swift_Current", "label" => "(UTC-06:00) America - Swift Current"),
      array("value" => "America/El_Salvador", "label" => "(UTC-06:00) America - El Salvador"),
      array("value" => "America/Guatemala", "label" => "(UTC-06:00) America - Guatemala"),
      array("value" => "America/Inuvik", "label" => "(UTC-06:00) America - Inuvik"),
      array("value" => "America/Managua", "label" => "(UTC-06:00) America - Managua"),
      array("value" => "America/Yellowknife", "label" => "(UTC-06:00) America - Yellowknife"),
      array("value" => "-0600", "label" => "(UTC-06:00) UTC/GMT-06:00"),
      array("value" => "America/Monterrey", "label" => "(UTC-05:00) America - Monterrey"),
      array("value" => "America/North_Dakota/Center", "label" => "(UTC-05:00) America - North Dakota - Center"),
      array("value" => "America/North_Dakota/New_Salem", "label" => "(UTC-05:00) America - North Dakota - New Salem"),
      array("value" => "America/Matamoros", "label" => "(UTC-05:00) America - Matamoros"),
      array("value" => "America/Bogota", "label" => "(UTC-05:00) America - Bogota"),
      array("value" => "America/North_Dakota/Beulah", "label" => "(UTC-05:00) America - North Dakota - Beulah"),
      array("value" => "America/Merida", "label" => "(UTC-05:00) America - Merida"),
      array("value" => "America/Cancun", "label" => "(UTC-05:00) America - Cancun"),
      array("value" => "America/Menominee", "label" => "(UTC-05:00) America - Menominee"),
      array("value" => "America/Cayman", "label" => "(UTC-05:00) America - Cayman"),
      array("value" => "America/Eirunepe", "label" => "(UTC-05:00) America - Eirunepe"),
      array("value" => "America/Mexico_City", "label" => "(UTC-05:00) America - Mexico City"),
      array("value" => "America/Guayaquil", "label" => "(UTC-05:00) America - Guayaquil"),
      array("value" => "America/Lima", "label" => "(UTC-05:00) America - Lima"),
      array("value" => "America/Jamaica", "label" => "(UTC-05:00) America - Jamaica"),
      array("value" => "America/Indiana/Tell_City", "label" => "(UTC-05:00) America - Indiana - Tell City"),
      array("value" => "America/Indiana/Knox", "label" => "(UTC-05:00) America - Indiana - Knox"),
      array("value" => "America/Bahia_Banderas", "label" => "(UTC-05:00) America - Bahia Banderas"),
      array("value" => "America/Chicago", "label" => "(UTC-05:00) America - Chicago"),
      array("value" => "America/Atikokan", "label" => "(UTC-05:00) America - Atikokan"),
      array("value" => "America/Winnipeg", "label" => "(UTC-05:00) America - Winnipeg"),
      array("value" => "America/Rio_Branco", "label" => "(UTC-05:00) America - Rio Branco"),
      array("value" => "America/Resolute", "label" => "(UTC-05:00) America - Resolute"),
      array("value" => "America/Rankin_Inlet", "label" => "(UTC-05:00) America - Rankin Inlet"),
      array("value" => "-0500", "label" => "(UTC-05:00) UTC/GMT-05:00"),
      array("value" => "America/Rainy_River", "label" => "(UTC-05:00) America - Rainy River"),
      array("value" => "America/Panama", "label" => "(UTC-05:00) America - Panama"),
      array("value" => "America/Santiago", "label" => "(UTC-04:00) America - Santiago"),
      array("value" => "America/Indiana/Petersburg", "label" => "(UTC-04:00) America - Indiana - Petersburg"),
      array("value" => "America/Guadeloupe", "label" => "(UTC-04:00) America - Guadeloupe"),
      array("value" => "America/Martinique", "label" => "(UTC-04:00) America - Martinique"),
      array("value" => "America/Thunder_Bay", "label" => "(UTC-04:00) America - Thunder Bay"),
      array("value" => "America/Guyana", "label" => "(UTC-04:00) America - Guyana"),
      array("value" => "America/Marigot", "label" => "(UTC-04:00) America - Marigot"),
      array("value" => "America/Havana", "label" => "(UTC-04:00) America - Havana"),
      array("value" => "America/Toronto", "label" => "(UTC-04:00) America - Toronto"),
      array("value" => "America/Indiana/Indianapolis", "label" => "(UTC-04:00) America - Indiana - Indianapolis"),
      array("value" => "America/Tortola", "label" => "(UTC-04:00) America - Tortola"),
      array("value" => "America/Indiana/Marengo", "label" => "(UTC-04:00) America - Indiana - Marengo"),
      array("value" => "America/Manaus", "label" => "(UTC-04:00) America - Manaus"),
      array("value" => "America/Lower_Princes", "label" => "(UTC-04:00) America - Lower Princes"),
      array("value" => "America/Indiana/Vevay", "label" => "(UTC-04:00) America - Indiana - Vevay"),
      array("value" => "America/Indiana/Vincennes", "label" => "(UTC-04:00) America - Indiana - Vincennes"),
      array("value" => "America/Asuncion", "label" => "(UTC-04:00) America - Asuncion"),
      array("value" => "America/Indiana/Winamac", "label" => "(UTC-04:00) America - Indiana - Winamac"),
      array("value" => "-0400", "label" => "(UTC-04:00) UTC/GMT-04:00"),
      array("value" => "America/Iqaluit", "label" => "(UTC-04:00) America - Iqaluit"),
      array("value" => "America/St_Kitts", "label" => "(UTC-04:00) America - St Kitts"),
      array("value" => "America/Kentucky/Louisville", "label" => "(UTC-04:00) America - Kentucky - Louisville"),
      array("value" => "America/Kentucky/Monticello", "label" => "(UTC-04:00) America - Kentucky - Monticello"),
      array("value" => "America/Kralendijk", "label" => "(UTC-04:00) America - Kralendijk"),
      array("value" => "America/La_Paz", "label" => "(UTC-04:00) America - La Paz"),
      array("value" => "America/Grenada", "label" => "(UTC-04:00) America - Grenada"),
      array("value" => "America/Grand_Turk", "label" => "(UTC-04:00) America - Grand Turk"),
      array("value" => "America/Montserrat", "label" => "(UTC-04:00) America - Montserrat"),
      array("value" => "America/St_Barthelemy", "label" => "(UTC-04:00) America - St Barthelemy"),
      array("value" => "America/Barbados", "label" => "(UTC-04:00) America - Barbados"),
      array("value" => "America/Aruba", "label" => "(UTC-04:00) America - Aruba"),
      array("value" => "America/Blanc-Sablon", "label" => "(UTC-04:00) America - Blanc-Sablon"),
      array("value" => "America/Boa_Vista", "label" => "(UTC-04:00) America - Boa Vista"),
      array("value" => "America/Pangnirtung", "label" => "(UTC-04:00) America - Pangnirtung"),
      array("value" => "America/Campo_Grande", "label" => "(UTC-04:00) America - Campo Grande"),
      array("value" => "America/Port-au-Prince", "label" => "(UTC-04:00) America - Port-au-Prince"),
      array("value" => "America/Caracas", "label" => "(UTC-04:00) America - Caracas"),
      array("value" => "America/Port_of_Spain", "label" => "(UTC-04:00) America - Port of Spain"),
      array("value" => "America/Porto_Velho", "label" => "(UTC-04:00) America - Porto Velho"),
      array("value" => "America/Nassau", "label" => "(UTC-04:00) America - Nassau"),
      array("value" => "America/Puerto_Rico", "label" => "(UTC-04:00) America - Puerto Rico"),
      array("value" => "America/Cuiaba", "label" => "(UTC-04:00) America - Cuiaba"),
      array("value" => "America/Anguilla", "label" => "(UTC-04:00) America - Anguilla"),
      array("value" => "America/New_York", "label" => "(UTC-04:00) America - New York"),
      array("value" => "America/Nipigon", "label" => "(UTC-04:00) America - Nipigon"),
      array("value" => "America/St_Vincent", "label" => "(UTC-04:00) America - St Vincent"),
      array("value" => "America/St_Thomas", "label" => "(UTC-04:00) America - St Thomas"),
      array("value" => "America/Curacao", "label" => "(UTC-04:00) America - Curacao"),
      array("value" => "America/Santo_Domingo", "label" => "(UTC-04:00) America - Santo Domingo"),
      array("value" => "America/Dominica", "label" => "(UTC-04:00) America - Dominica"),
      array("value" => "America/Detroit", "label" => "(UTC-04:00) America - Detroit"),
      array("value" => "America/Antigua", "label" => "(UTC-04:00) America - Antigua"),
      array("value" => "America/St_Lucia", "label" => "(UTC-04:00) America - St Lucia"),
      array("value" => "-0330", "label" => "(UTC-03:30) UTC/GMT-03:30"),
      array("value" => "America/Moncton", "label" => "(UTC-03:00) America - Moncton"),
      array("value" => "America/Santarem", "label" => "(UTC-03:00) America - Santarem"),
      array("value" => "America/Paramaribo", "label" => "(UTC-03:00) America - Paramaribo"),
      array("value" => "America/Montevideo", "label" => "(UTC-03:00) America - Montevideo"),
      array("value" => "America/Recife", "label" => "(UTC-03:00) America - Recife"),
      array("value" => "America/Punta_Arenas", "label" => "(UTC-03:00) America - Punta Arenas"),
      array("value" => "America/Sao_Paulo", "label" => "(UTC-03:00) America - Sao Paulo"),
      array("value" => "Atlantic/Stanley", "label" => "(UTC-03:00) Atlantic - Stanley"),
      array("value" => "America/Goose_Bay", "label" => "(UTC-03:00) America - Goose Bay"),
      array("value" => "America/Maceio", "label" => "(UTC-03:00) America - Maceio"),
      array("value" => "America/Argentina/Tucuman", "label" => "(UTC-03:00) America - Argentina - Tucuman"),
      array("value" => "Antarctica/Rothera", "label" => "(UTC-03:00) Antarctica - Rothera"),
      array("value" => "Antarctica/Palmer", "label" => "(UTC-03:00) Antarctica - Palmer"),
      array("value" => "-0300", "label" => "(UTC-03:00) UTC/GMT-03:00"),
      array("value" => "America/Thule", "label" => "(UTC-03:00) America - Thule"),
      array("value" => "America/Araguaina", "label" => "(UTC-03:00) America - Araguaina"),
      array("value" => "America/Argentina/Buenos_Aires", "label" => "(UTC-03:00) America - Argentina - Buenos Aires"),
      array("value" => "America/Argentina/Catamarca", "label" => "(UTC-03:00) America - Argentina - Catamarca"),
      array("value" => "America/Argentina/Cordoba", "label" => "(UTC-03:00) America - Argentina - Cordoba"),
      array("value" => "America/Argentina/Jujuy", "label" => "(UTC-03:00) America - Argentina - Jujuy"),
      array("value" => "America/Argentina/La_Rioja", "label" => "(UTC-03:00) America - Argentina - La Rioja"),
      array("value" => "America/Argentina/Mendoza", "label" => "(UTC-03:00) America - Argentina - Mendoza"),
      array("value" => "America/Argentina/Rio_Gallegos", "label" => "(UTC-03:00) America - Argentina - Rio Gallegos"),
      array("value" => "America/Argentina/Salta", "label" => "(UTC-03:00) America - Argentina - Salta"),
      array("value" => "America/Argentina/San_Juan", "label" => "(UTC-03:00) America - Argentina - San Juan"),
      array("value" => "America/Argentina/San_Luis", "label" => "(UTC-03:00) America - Argentina - San Luis"),
      array("value" => "America/Argentina/Ushuaia", "label" => "(UTC-03:00) America - Argentina - Ushuaia"),
      array("value" => "America/Bahia", "label" => "(UTC-03:00) America - Bahia"),
      array("value" => "America/Belem", "label" => "(UTC-03:00) America - Belem"),
      array("value" => "America/Cayenne", "label" => "(UTC-03:00) America - Cayenne"),
      array("value" => "Atlantic/Bermuda", "label" => "(UTC-03:00) Atlantic - Bermuda"),
      array("value" => "America/Halifax", "label" => "(UTC-03:00) America - Halifax"),
      array("value" => "America/Fortaleza", "label" => "(UTC-03:00) America - Fortaleza"),
      array("value" => "America/Glace_Bay", "label" => "(UTC-03:00) America - Glace Bay"),
      array("value" => "America/St_Johns", "label" => "(UTC-02:30) America - St Johns"),
      array("value" => "America/Miquelon", "label" => "(UTC-02:00) America - Miquelon"),
      array("value" => "America/Godthab", "label" => "(UTC-02:00) America - Godthab"),
      array("value" => "Atlantic/South_Georgia", "label" => "(UTC-02:00) Atlantic - South Georgia"),
      array("value" => "America/Noronha", "label" => "(UTC-02:00) America - Noronha"),
      array("value" => "-0200", "label" => "(UTC-02:00) UTC/GMT-02:00"),
      array("value" => "-0100", "label" => "(UTC-01:00) UTC/GMT-01:00"),
      array("value" => "Atlantic/Cape_Verde", "label" => "(UTC-01:00) Atlantic - Cape Verde"),
      array("value" => "Atlantic/St_Helena", "label" => "(UTC) Atlantic - St Helena"),
      array("value" => "UTC", "label" => "(UTC) UTC"),
      array("value" => "Atlantic/Azores", "label" => "(UTC) Atlantic - Azores"),
      array("value" => "Atlantic/Reykjavik", "label" => "(UTC) Atlantic - Reykjavik"),
      array("value" => "Africa/Accra", "label" => "(UTC) Africa - Accra"),
      array("value" => "Africa/Abidjan", "label" => "(UTC) Africa - Abidjan"),
      array("value" => "America/Scoresbysund", "label" => "(UTC) America - Scoresbysund"),
      array("value" => "Africa/Monrovia", "label" => "(UTC) Africa - Monrovia"),
      array("value" => "Africa/Freetown", "label" => "(UTC) Africa - Freetown"),
      array("value" => "Africa/Bissau", "label" => "(UTC) Africa - Bissau"),
      array("value" => "Africa/Banjul", "label" => "(UTC) Africa - Banjul"),
      array("value" => "Africa/Bamako", "label" => "(UTC) Africa - Bamako"),
      array("value" => "Africa/Lome", "label" => "(UTC) Africa - Lome"),
      array("value" => "Africa/Dakar", "label" => "(UTC) Africa - Dakar"),
      array("value" => "Africa/Conakry", "label" => "(UTC) Africa - Conakry"),
      array("value" => "Africa/Nouakchott", "label" => "(UTC) Africa - Nouakchott"),
      array("value" => "Africa/Sao_Tome", "label" => "(UTC) Africa - Sao Tome"),
      array("value" => "Africa/Ouagadougou", "label" => "(UTC) Africa - Ouagadougou"),
      array("value" => "America/Danmarkshavn", "label" => "(UTC) America - Danmarkshavn"),
      array("value" => "Africa/Libreville", "label" => "(UTC+01:00) Africa - Libreville"),
      array("value" => "Africa/Luanda", "label" => "(UTC+01:00) Africa - Luanda"),
      array("value" => "+0100", "label" => "(UTC+01:00) UTC/GMT+01:00"),
      array("value" => "Africa/Lagos", "label" => "(UTC+01:00) Africa - Lagos"),
      array("value" => "Atlantic/Madeira", "label" => "(UTC+01:00) Atlantic - Madeira"),
      array("value" => "Africa/Niamey", "label" => "(UTC+01:00) Africa - Niamey"),
      array("value" => "Atlantic/Faroe", "label" => "(UTC+01:00) Atlantic - Faroe"),
      array("value" => "Africa/Bangui", "label" => "(UTC+01:00) Africa - Bangui"),
      array("value" => "Atlantic/Canary", "label" => "(UTC+01:00) Atlantic - Canary"),
      array("value" => "Africa/Tunis", "label" => "(UTC+01:00) Africa - Tunis"),
      array("value" => "Africa/Porto-Novo", "label" => "(UTC+01:00) Africa - Porto-Novo"),
      array("value" => "Africa/Kinshasa", "label" => "(UTC+01:00) Africa - Kinshasa"),
      array("value" => "Europe/Dublin", "label" => "(UTC+01:00) Europe - Dublin"),
      array("value" => "Europe/Guernsey", "label" => "(UTC+01:00) Europe - Guernsey"),
      array("value" => "Africa/Malabo", "label" => "(UTC+01:00) Africa - Malabo"),
      array("value" => "Africa/Ndjamena", "label" => "(UTC+01:00) Africa - Ndjamena"),
      array("value" => "Africa/Douala", "label" => "(UTC+01:00) Africa - Douala"),
      array("value" => "Africa/El_Aaiun", "label" => "(UTC+01:00) Africa - El Aaiun"),
      array("value" => "Africa/Casablanca", "label" => "(UTC+01:00) Africa - Casablanca"),
      array("value" => "Europe/London", "label" => "(UTC+01:00) Europe - London"),
      array("value" => "Europe/Lisbon", "label" => "(UTC+01:00) Europe - Lisbon"),
      array("value" => "Africa/Brazzaville", "label" => "(UTC+01:00) Africa - Brazzaville"),
      array("value" => "Europe/Jersey", "label" => "(UTC+01:00) Europe - Jersey"),
      array("value" => "Europe/Isle_of_Man", "label" => "(UTC+01:00) Europe - Isle of Man"),
      array("value" => "Africa/Algiers", "label" => "(UTC+01:00) Africa - Algiers"),
      array("value" => "Europe/Prague", "label" => "(UTC+02:00) Europe - Prague"),
      array("value" => "Africa/Blantyre", "label" => "(UTC+02:00) Africa - Blantyre"),
      array("value" => "Europe/Vatican", "label" => "(UTC+02:00) Europe - Vatican"),
      array("value" => "Africa/Bujumbura", "label" => "(UTC+02:00) Africa - Bujumbura"),
      array("value" => "Europe/Vienna", "label" => "(UTC+02:00) Europe - Vienna"),
      array("value" => "Africa/Cairo", "label" => "(UTC+02:00) Africa - Cairo"),
      array("value" => "Europe/Warsaw", "label" => "(UTC+02:00) Europe - Warsaw"),
      array("value" => "Africa/Ceuta", "label" => "(UTC+02:00) Africa - Ceuta"),
      array("value" => "Europe/Zagreb", "label" => "(UTC+02:00) Europe - Zagreb"),
      array("value" => "Europe/Zurich", "label" => "(UTC+02:00) Europe - Zurich"),
      array("value" => "Europe/Stockholm", "label" => "(UTC+02:00) Europe - Stockholm"),
      array("value" => "Europe/Podgorica", "label" => "(UTC+02:00) Europe - Podgorica"),
      array("value" => "Europe/Copenhagen", "label" => "(UTC+02:00) Europe - Copenhagen"),
      array("value" => "Europe/Paris", "label" => "(UTC+02:00) Europe - Paris"),
      array("value" => "Europe/Oslo", "label" => "(UTC+02:00) Europe - Oslo"),
      array("value" => "Europe/Monaco", "label" => "(UTC+02:00) Europe - Monaco"),
      array("value" => "Europe/Malta", "label" => "(UTC+02:00) Europe - Malta"),
      array("value" => "Europe/Madrid", "label" => "(UTC+02:00) Europe - Madrid"),
      array("value" => "Europe/Luxembourg", "label" => "(UTC+02:00) Europe - Luxembourg"),
      array("value" => "Europe/Ljubljana", "label" => "(UTC+02:00) Europe - Ljubljana"),
      array("value" => "Europe/Kaliningrad", "label" => "(UTC+02:00) Europe - Kaliningrad"),
      array("value" => "Europe/Gibraltar", "label" => "(UTC+02:00) Europe - Gibraltar"),
      array("value" => "Europe/Busingen", "label" => "(UTC+02:00) Europe - Busingen"),
      array("value" => "Europe/Vaduz", "label" => "(UTC+02:00) Europe - Vaduz"),
      array("value" => "Europe/Budapest", "label" => "(UTC+02:00) Europe - Budapest"),
      array("value" => "Europe/Brussels", "label" => "(UTC+02:00) Europe - Brussels"),
      array("value" => "Europe/Bratislava", "label" => "(UTC+02:00) Europe - Bratislava"),
      array("value" => "Europe/Berlin", "label" => "(UTC+02:00) Europe - Berlin"),
      array("value" => "Europe/Belgrade", "label" => "(UTC+02:00) Europe - Belgrade"),
      array("value" => "Europe/Amsterdam", "label" => "(UTC+02:00) Europe - Amsterdam"),
      array("value" => "Europe/San_Marino", "label" => "(UTC+02:00) Europe - San Marino"),
      array("value" => "Europe/Sarajevo", "label" => "(UTC+02:00) Europe - Sarajevo"),
      array("value" => "Europe/Skopje", "label" => "(UTC+02:00) Europe - Skopje"),
      array("value" => "Europe/Tirane", "label" => "(UTC+02:00) Europe - Tirane"),
      array("value" => "Europe/Andorra", "label" => "(UTC+02:00) Europe - Andorra"),
      array("value" => "Europe/Rome", "label" => "(UTC+02:00) Europe - Rome"),
      array("value" => "Antarctica/Troll", "label" => "(UTC+02:00) Antarctica - Troll"),
      array("value" => "Africa/Harare", "label" => "(UTC+02:00) Africa - Harare"),
      array("value" => "Arctic/Longyearbyen", "label" => "(UTC+02:00) Arctic - Longyearbyen"),
      array("value" => "Africa/Lubumbashi", "label" => "(UTC+02:00) Africa - Lubumbashi"),
      array("value" => "Africa/Johannesburg", "label" => "(UTC+02:00) Africa - Johannesburg"),
      array("value" => "Africa/Lusaka", "label" => "(UTC+02:00) Africa - Lusaka"),
      array("value" => "Africa/Maputo", "label" => "(UTC+02:00) Africa - Maputo"),
      array("value" => "Africa/Khartoum", "label" => "(UTC+02:00) Africa - Khartoum"),
      array("value" => "Africa/Maseru", "label" => "(UTC+02:00) Africa - Maseru"),
      array("value" => "Africa/Mbabane", "label" => "(UTC+02:00) Africa - Mbabane"),
      array("value" => "Africa/Gaborone", "label" => "(UTC+02:00) Africa - Gaborone"),
      array("value" => "Africa/Windhoek", "label" => "(UTC+02:00) Africa - Windhoek"),
      array("value" => "Africa/Tripoli", "label" => "(UTC+02:00) Africa - Tripoli"),
      array("value" => "Africa/Kigali", "label" => "(UTC+02:00) Africa - Kigali"),
      array("value" => "+0200", "label" => "(UTC+02:00) UTC/GMT+02:00"),
      array("value" => "+0300", "label" => "(UTC+03:00) UTC/GMT+03:00"),
      array("value" => "Africa/Djibouti", "label" => "(UTC+03:00) Africa - Djibouti"),
      array("value" => "Europe/Bucharest", "label" => "(UTC+03:00) Europe - Bucharest"),
      array("value" => "Europe/Sofia", "label" => "(UTC+03:00) Europe - Sofia"),
      array("value" => "Europe/Simferopol", "label" => "(UTC+03:00) Europe - Simferopol"),
      array("value" => "Asia/Bahrain", "label" => "(UTC+03:00) Asia - Bahrain"),
      array("value" => "Europe/Tallinn", "label" => "(UTC+03:00) Europe - Tallinn"),
      array("value" => "Asia/Beirut", "label" => "(UTC+03:00) Asia - Beirut"),
      array("value" => "Africa/Addis_Ababa", "label" => "(UTC+03:00) Africa - Addis Ababa"),
      array("value" => "Asia/Baghdad", "label" => "(UTC+03:00) Asia - Baghdad"),
      array("value" => "Europe/Athens", "label" => "(UTC+03:00) Europe - Athens"),
      array("value" => "Africa/Dar_es_Salaam", "label" => "(UTC+03:00) Africa - Dar es Salaam"),
      array("value" => "Asia/Amman", "label" => "(UTC+03:00) Asia - Amman"),
      array("value" => "Europe/Chisinau", "label" => "(UTC+03:00) Europe - Chisinau"),
      array("value" => "Asia/Aden", "label" => "(UTC+03:00) Asia - Aden"),
      array("value" => "Asia/Damascus", "label" => "(UTC+03:00) Asia - Damascus"),
      array("value" => "Europe/Helsinki", "label" => "(UTC+03:00) Europe - Helsinki"),
      array("value" => "Antarctica/Syowa", "label" => "(UTC+03:00) Antarctica - Syowa"),
      array("value" => "Europe/Istanbul", "label" => "(UTC+03:00) Europe - Istanbul"),
      array("value" => "Europe/Kiev", "label" => "(UTC+03:00) Europe - Kiev"),
      array("value" => "Europe/Kirov", "label" => "(UTC+03:00) Europe - Kirov"),
      array("value" => "Europe/Mariehamn", "label" => "(UTC+03:00) Europe - Mariehamn"),
      array("value" => "Europe/Minsk", "label" => "(UTC+03:00) Europe - Minsk"),
      array("value" => "Europe/Moscow", "label" => "(UTC+03:00) Europe - Moscow"),
      array("value" => "Africa/Mogadishu", "label" => "(UTC+03:00) Africa - Mogadishu"),
      array("value" => "Africa/Nairobi", "label" => "(UTC+03:00) Africa - Nairobi"),
      array("value" => "Europe/Riga", "label" => "(UTC+03:00) Europe - Riga"),
      array("value" => "Africa/Asmara", "label" => "(UTC+03:00) Africa - Asmara"),
      array("value" => "Europe/Uzhgorod", "label" => "(UTC+03:00) Europe - Uzhgorod"),
      array("value" => "Asia/Qatar", "label" => "(UTC+03:00) Asia - Qatar"),
      array("value" => "Africa/Kampala", "label" => "(UTC+03:00) Africa - Kampala"),
      array("value" => "Africa/Juba", "label" => "(UTC+03:00) Africa - Juba"),
      array("value" => "Indian/Mayotte", "label" => "(UTC+03:00) Indian - Mayotte"),
      array("value" => "Asia/Riyadh", "label" => "(UTC+03:00) Asia - Riyadh"),
      array("value" => "Indian/Antananarivo", "label" => "(UTC+03:00) Indian - Antananarivo"),
      array("value" => "Europe/Vilnius", "label" => "(UTC+03:00) Europe - Vilnius"),
      array("value" => "Asia/Jerusalem", "label" => "(UTC+03:00) Asia - Jerusalem"),
      array("value" => "Asia/Nicosia", "label" => "(UTC+03:00) Asia - Nicosia"),
      array("value" => "Indian/Comoro", "label" => "(UTC+03:00) Indian - Comoro"),
      array("value" => "Asia/Hebron", "label" => "(UTC+03:00) Asia - Hebron"),
      array("value" => "Asia/Gaza", "label" => "(UTC+03:00) Asia - Gaza"),
      array("value" => "Asia/Famagusta", "label" => "(UTC+03:00) Asia - Famagusta"),
      array("value" => "Asia/Kuwait", "label" => "(UTC+03:00) Asia - Kuwait"),
      array("value" => "Europe/Zaporozhye", "label" => "(UTC+03:00) Europe - Zaporozhye"),
      array("value" => "+0330", "label" => "(UTC+03:30) UTC/GMT+03:30"),
      array("value" => "Indian/Mahe", "label" => "(UTC+04:00) Indian - Mahe"),
      array("value" => "Indian/Reunion", "label" => "(UTC+04:00) Indian - Reunion"),
      array("value" => "Indian/Mauritius", "label" => "(UTC+04:00) Indian - Mauritius"),
      array("value" => "Europe/Samara", "label" => "(UTC+04:00) Europe - Samara"),
      array("value" => "Asia/Muscat", "label" => "(UTC+04:00) Asia - Muscat"),
      array("value" => "Asia/Tbilisi", "label" => "(UTC+04:00) Asia - Tbilisi"),
      array("value" => "Asia/Dubai", "label" => "(UTC+04:00) Asia - Dubai"),
      array("value" => "Europe/Saratov", "label" => "(UTC+04:00) Europe - Saratov"),
      array("value" => "Europe/Ulyanovsk", "label" => "(UTC+04:00) Europe - Ulyanovsk"),
      array("value" => "Asia/Yerevan", "label" => "(UTC+04:00) Asia - Yerevan"),
      array("value" => "+0400", "label" => "(UTC+04:00) UTC/GMT+04:00"),
      array("value" => "Europe/Astrakhan", "label" => "(UTC+04:00) Europe - Astrakhan"),
      array("value" => "Europe/Volgograd", "label" => "(UTC+04:00) Europe - Volgograd"),
      array("value" => "Asia/Baku", "label" => "(UTC+04:00) Asia - Baku"),
      array("value" => "Asia/Tehran", "label" => "(UTC+04:30) Asia - Tehran"),
      array("value" => "Asia/Kabul", "label" => "(UTC+04:30) Asia - Kabul"),
      array("value" => "+0430", "label" => "(UTC+04:30) UTC/GMT+04:30"),
      array("value" => "Asia/Oral", "label" => "(UTC+05:00) Asia - Oral"),
      array("value" => "Asia/Karachi", "label" => "(UTC+05:00) Asia - Karachi"),
      array("value" => "Asia/Yekaterinburg", "label" => "(UTC+05:00) Asia - Yekaterinburg"),
      array("value" => "Asia/Aqtau", "label" => "(UTC+05:00) Asia - Aqtau"),
      array("value" => "+0500", "label" => "(UTC+05:00) UTC/GMT+05:00"),
      array("value" => "Asia/Qyzylorda", "label" => "(UTC+05:00) Asia - Qyzylorda"),
      array("value" => "Asia/Ashgabat", "label" => "(UTC+05:00) Asia - Ashgabat"),
      array("value" => "Asia/Dushanbe", "label" => "(UTC+05:00) Asia - Dushanbe"),
      array("value" => "Asia/Aqtobe", "label" => "(UTC+05:00) Asia - Aqtobe"),
      array("value" => "Asia/Samarkand", "label" => "(UTC+05:00) Asia - Samarkand"),
      array("value" => "Asia/Tashkent", "label" => "(UTC+05:00) Asia - Tashkent"),
      array("value" => "Indian/Kerguelen", "label" => "(UTC+05:00) Indian - Kerguelen"),
      array("value" => "Indian/Maldives", "label" => "(UTC+05:00) Indian - Maldives"),
      array("value" => "Asia/Atyrau", "label" => "(UTC+05:00) Asia - Atyrau"),
      array("value" => "Antarctica/Mawson", "label" => "(UTC+05:00) Antarctica - Mawson"),
      array("value" => "+0530", "label" => "(UTC+05:30) UTC/GMT+05:30"),
      array("value" => "Asia/Kolkata", "label" => "(UTC+05:30) Asia - Kolkata"),
      array("value" => "Asia/Colombo", "label" => "(UTC+05:30) Asia - Colombo"),
      array("value" => "+0545", "label" => "(UTC+05:45) UTC/GMT+05:45"),
      array("value" => "Asia/Kathmandu", "label" => "(UTC+05:45) Asia - Kathmandu"),
      array("value" => "+0600", "label" => "(UTC+06:00) UTC/GMT+06:00"),
      array("value" => "Indian/Chagos", "label" => "(UTC+06:00) Indian - Chagos"),
      array("value" => "Asia/Dhaka", "label" => "(UTC+06:00) Asia - Dhaka"),
      array("value" => "Asia/Bishkek", "label" => "(UTC+06:00) Asia - Bishkek"),
      array("value" => "Asia/Qostanay", "label" => "(UTC+06:00) Asia - Qostanay"),
      array("value" => "Asia/Urumqi", "label" => "(UTC+06:00) Asia - Urumqi"),
      array("value" => "Asia/Almaty", "label" => "(UTC+06:00) Asia - Almaty"),
      array("value" => "Asia/Omsk", "label" => "(UTC+06:00) Asia - Omsk"),
      array("value" => "Asia/Thimphu", "label" => "(UTC+06:00) Asia - Thimphu"),
      array("value" => "Antarctica/Vostok", "label" => "(UTC+06:00) Antarctica - Vostok"),
      array("value" => "Asia/Yangon", "label" => "(UTC+06:30) Asia - Yangon"),
      array("value" => "Indian/Cocos", "label" => "(UTC+06:30) Indian - Cocos"),
      array("value" => "Asia/Bangkok", "label" => "(UTC+07:00) Asia - Bangkok"),
      array("value" => "Antarctica/Davis", "label" => "(UTC+07:00) Antarctica - Davis"),
      array("value" => "Asia/Pontianak", "label" => "(UTC+07:00) Asia - Pontianak"),
      array("value" => "Asia/Novosibirsk", "label" => "(UTC+07:00) Asia - Novosibirsk"),
      array("value" => "Asia/Novokuznetsk", "label" => "(UTC+07:00) Asia - Novokuznetsk"),
      array("value" => "Asia/Krasnoyarsk", "label" => "(UTC+07:00) Asia - Krasnoyarsk"),
      array("value" => "+0700", "label" => "(UTC+07:00) UTC/GMT+07:00"),
      array("value" => "Asia/Jakarta", "label" => "(UTC+07:00) Asia - Jakarta"),
      array("value" => "Asia/Hovd", "label" => "(UTC+07:00) Asia - Hovd"),
      array("value" => "Asia/Ho_Chi_Minh", "label" => "(UTC+07:00) Asia - Ho Chi Minh"),
      array("value" => "Asia/Barnaul", "label" => "(UTC+07:00) Asia - Barnaul"),
      array("value" => "Indian/Christmas", "label" => "(UTC+07:00) Indian - Christmas"),
      array("value" => "Asia/Phnom_Penh", "label" => "(UTC+07:00) Asia - Phnom Penh"),
      array("value" => "Asia/Tomsk", "label" => "(UTC+07:00) Asia - Tomsk"),
      array("value" => "Asia/Vientiane", "label" => "(UTC+07:00) Asia - Vientiane"),
      array("value" => "Asia/Irkutsk", "label" => "(UTC+08:00) Asia - Irkutsk"),
      array("value" => "Asia/Makassar", "label" => "(UTC+08:00) Asia - Makassar"),
      array("value" => "Asia/Macau", "label" => "(UTC+08:00) Asia - Macau"),
      array("value" => "Asia/Kuching", "label" => "(UTC+08:00) Asia - Kuching"),
      array("value" => "+0800", "label" => "(UTC+08:00) UTC/GMT+08:00"),
      array("value" => "Asia/Kuala_Lumpur", "label" => "(UTC+08:00) Asia - Kuala Lumpur"),
      array("value" => "Antarctica/Casey", "label" => "(UTC+08:00) Antarctica - Casey"),
      array("value" => "Australia/Perth", "label" => "(UTC+08:00) Australia - Perth"),
      array("value" => "Asia/Manila", "label" => "(UTC+08:00) Asia - Manila"),
      array("value" => "Asia/Hong_Kong", "label" => "(UTC+08:00) Asia - Hong Kong"),
      array("value" => "Asia/Ulaanbaatar", "label" => "(UTC+08:00) Asia - Ulaanbaatar"),
      array("value" => "Asia/Choibalsan", "label" => "(UTC+08:00) Asia - Choibalsan"),
      array("value" => "Asia/Shanghai", "label" => "(UTC+08:00) Asia - Shanghai"),
      array("value" => "Asia/Singapore", "label" => "(UTC+08:00) Asia - Singapore"),
      array("value" => "Asia/Brunei", "label" => "(UTC+08:00) Asia - Brunei"),
      array("value" => "Asia/Taipei", "label" => "(UTC+08:00) Asia - Taipei"),
      array("value" => "+0844", "label" => "(UTC+08:44) UTC/GMT+08:44"),
      array("value" => "Australia/Eucla", "label" => "(UTC+08:45) Australia - Eucla"),
      array("value" => "Asia/Dili", "label" => "(UTC+09:00) Asia - Dili"),
      array("value" => "Asia/Jayapura", "label" => "(UTC+09:00) Asia - Jayapura"),
      array("value" => "Asia/Khandyga", "label" => "(UTC+09:00) Asia - Khandyga"),
      array("value" => "Asia/Chita", "label" => "(UTC+09:00) Asia - Chita"),
      array("value" => "+0900", "label" => "(UTC+09:00) UTC/GMT+09:00"),
      array("value" => "Pacific/Palau", "label" => "(UTC+09:00) Pacific - Palau"),
      array("value" => "Asia/Tokyo", "label" => "(UTC+09:00) Asia - Tokyo"),
      array("value" => "Asia/Yakutsk", "label" => "(UTC+09:00) Asia - Yakutsk"),
      array("value" => "Asia/Seoul", "label" => "(UTC+09:00) Asia - Seoul"),
      array("value" => "Asia/Pyongyang", "label" => "(UTC+09:00) Asia - Pyongyang"),
      array("value" => "Australia/Adelaide", "label" => "(UTC+09:30) Australia - Adelaide"),
      array("value" => "Australia/Broken_Hill", "label" => "(UTC+09:30) Australia - Broken Hill"),
      array("value" => "+0930", "label" => "(UTC+09:30) UTC/GMT+09:30"),
      array("value" => "Australia/Darwin", "label" => "(UTC+09:30) Australia - Darwin"),
      array("value" => "+1000", "label" => "(UTC+10:00) UTC/GMT+10:00"),
      array("value" => "Australia/Melbourne", "label" => "(UTC+10:00) Australia - Melbourne"),
      array("value" => "Australia/Lindeman", "label" => "(UTC+10:00) Australia - Lindeman"),
      array("value" => "Australia/Hobart", "label" => "(UTC+10:00) Australia - Hobart"),
      array("value" => "Pacific/Chuuk", "label" => "(UTC+10:00) Pacific - Chuuk"),
      array("value" => "Australia/Currie", "label" => "(UTC+10:00) Australia - Currie"),
      array("value" => "Asia/Ust-Nera", "label" => "(UTC+10:00) Asia - Ust-Nera"),
      array("value" => "Antarctica/DumontDUrville", "label" => "(UTC+10:00) Antarctica - DumontDUrville"),
      array("value" => "Australia/Sydney", "label" => "(UTC+10:00) Australia - Sydney"),
      array("value" => "Australia/Brisbane", "label" => "(UTC+10:00) Australia - Brisbane"),
      array("value" => "Pacific/Saipan", "label" => "(UTC+10:00) Pacific - Saipan"),
      array("value" => "Pacific/Port_Moresby", "label" => "(UTC+10:00) Pacific - Port Moresby"),
      array("value" => "Pacific/Guam", "label" => "(UTC+10:00) Pacific - Guam"),
      array("value" => "Asia/Vladivostok", "label" => "(UTC+10:00) Asia - Vladivostok"),
      array("value" => "+1030", "label" => "(UTC+10:30) UTC/GMT+10:30"),
      array("value" => "Australia/Lord_Howe", "label" => "(UTC+10:30) Australia - Lord Howe"),
      array("value" => "+1100", "label" => "(UTC+11:00) UTC/GMT+11:00"),
      array("value" => "Asia/Srednekolymsk", "label" => "(UTC+11:00) Asia - Srednekolymsk"),
      array("value" => "Pacific/Kosrae", "label" => "(UTC+11:00) Pacific - Kosrae"),
      array("value" => "Asia/Sakhalin", "label" => "(UTC+11:00) Asia - Sakhalin"),
      array("value" => "Pacific/Bougainville", "label" => "(UTC+11:00) Pacific - Bougainville"),
      array("value" => "Pacific/Norfolk", "label" => "(UTC+11:00) Pacific - Norfolk"),
      array("value" => "Pacific/Noumea", "label" => "(UTC+11:00) Pacific - Noumea"),
      array("value" => "Asia/Magadan", "label" => "(UTC+11:00) Asia - Magadan"),
      array("value" => "Pacific/Pohnpei", "label" => "(UTC+11:00) Pacific - Pohnpei"),
      array("value" => "Pacific/Efate", "label" => "(UTC+11:00) Pacific - Efate"),
      array("value" => "Pacific/Guadalcanal", "label" => "(UTC+11:00) Pacific - Guadalcanal"),
      array("value" => "Antarctica/Macquarie", "label" => "(UTC+11:00) Antarctica - Macquarie"),
      array("value" => "Antarctica/McMurdo", "label" => "(UTC+12:00) Antarctica - McMurdo"),
      array("value" => "+1200", "label" => "(UTC+12:00) UTC/GMT+12:00"),
      array("value" => "Pacific/Nauru", "label" => "(UTC+12:00) Pacific - Nauru"),
      array("value" => "Asia/Anadyr", "label" => "(UTC+12:00) Asia - Anadyr"),
      array("value" => "Asia/Kamchatka", "label" => "(UTC+12:00) Asia - Kamchatka"),
      array("value" => "Pacific/Auckland", "label" => "(UTC+12:00) Pacific - Auckland"),
      array("value" => "Pacific/Fiji", "label" => "(UTC+12:00) Pacific - Fiji"),
      array("value" => "Pacific/Funafuti", "label" => "(UTC+12:00) Pacific - Funafuti"),
      array("value" => "Pacific/Kwajalein", "label" => "(UTC+12:00) Pacific - Kwajalein"),
      array("value" => "Pacific/Majuro", "label" => "(UTC+12:00) Pacific - Majuro"),
      array("value" => "Pacific/Tarawa", "label" => "(UTC+12:00) Pacific - Tarawa"),
      array("value" => "Pacific/Wake", "label" => "(UTC+12:00) Pacific - Wake"),
      array("value" => "Pacific/Wallis", "label" => "(UTC+12:00) Pacific - Wallis"),
      array("value" => "Pacific/Chatham", "label" => "(UTC+12:45) Pacific - Chatham"),
      array("value" => "+1245", "label" => "(UTC+12:45) UTC/GMT+12:45"),
      array("value" => "+1300", "label" => "(UTC+13:00) UTC/GMT+13:00"),
      array("value" => "Pacific/Tongatapu", "label" => "(UTC+13:00) Pacific - Tongatapu"),
      array("value" => "Pacific/Fakaofo", "label" => "(UTC+13:00) Pacific - Fakaofo"),
      array("value" => "Pacific/Enderbury", "label" => "(UTC+13:00) Pacific - Enderbury"),
      array("value" => "Pacific/Apia", "label" => "(UTC+13:00) Pacific - Apia"),
      array("value" => "+1400", "label" => "(UTC+14:00) UTC/GMT+14:00"),
      array("value" => "Pacific/Kiritimati", "label" => "(UTC+14:00) Pacific - Kiritimati")
    ),
    'month' => array(
      array('value' => '1', 'label' => 'Jan'),
      array('value' => '2', 'label' => 'Feb'),
      array('value' => '3', 'label' => 'Mar'),
      array('value' => '4', 'label' => 'Apr'),
      array('value' => '5', 'label' => 'May'),
      array('value' => '6', 'label' => 'Jun'),
      array('value' => '7', 'label' => 'Jul'),
      array('value' => '8', 'label' => 'Aug'),
      array('value' => '9', 'label' => 'Sep'),
      array('value' => '10', 'label' => 'Oct'),
      array('value' => '11', 'label' => 'Nov'),
      array('value' => '12', 'label' => 'Dec')
    ),
    'day' => array(
      array('value' => '01', 'label' => '1'),
      array('value' => '02', 'label' => '2'),
      array('value' => '03', 'label' => '3'),
      array('value' => '04', 'label' => '4'),
      array('value' => '05', 'label' => '5'),
      array('value' => '06', 'label' => '6'),
      array('value' => '07', 'label' => '7'),
      array('value' => '08', 'label' => '8'),
      array('value' => '09', 'label' => '9'),
      array('value' => '10', 'label' => '10'),
      array('value' => '11', 'label' => '11'),
      array('value' => '12', 'label' => '12'),
      array('value' => '13', 'label' => '13'),
      array('value' => '14', 'label' => '14'),
      array('value' => '15', 'label' => '15'),
      array('value' => '16', 'label' => '16'),
      array('value' => '17', 'label' => '17'),
      array('value' => '18', 'label' => '18'),
      array('value' => '19', 'label' => '19'),
      array('value' => '20', 'label' => '20'),
      array('value' => '21', 'label' => '21'),
      array('value' => '22', 'label' => '22'),
      array('value' => '23', 'label' => '23'),
      array('value' => '24', 'label' => '24'),
      array('value' => '25', 'label' => '25'),
      array('value' => '26', 'label' => '26'),
      array('value' => '27', 'label' => '27'),
      array('value' => '28', 'label' => '28'),
      array('value' => '29', 'label' => '29'),
      array('value' => '30', 'label' => '30'),
      array('value' => '31', 'label' => '31')
    ),
    'year' => array(
      array('value' => '2019', 'label' => '2019'),
      array('value' => '2020', 'label' => '2020'),
      array('value' => '2021', 'label' => '2021'),
      array('value' => '2022', 'label' => '2022'),
      array('value' => '2023', 'label' => '2023')
    ),
    'hour' => array(
      array('value' => '1', 'label' => '1'),
      array('value' => '2', 'label' => '2'),
      array('value' => '3', 'label' => '3'),
      array('value' => '4', 'label' => '4'),
      array('value' => '5', 'label' => '5'),
      array('value' => '6', 'label' => '6'),
      array('value' => '7', 'label' => '7'),
      array('value' => '8', 'label' => '8'),
      array('value' => '9', 'label' => '9'),
      array('value' => '10', 'label' => '10'),
      array('value' => '11', 'label' => '11'),
      array('value' => '12', 'label' => '12')
    ),
    'min' => array(
      array('value' => '00', 'label' => '00' , 'selected' => true),
      array('value' => '05', 'label' => '05'),
      array('value' => '10', 'label' => '10'),
      array('value' => '15', 'label' => '15'),
      array('value' => '20', 'label' => '20'),
      array('value' => '25', 'label' => '25'),
      array('value' => '30', 'label' => '30'),
      array('value' => '35', 'label' => '35'),
      array('value' => '40', 'label' => '40'),
      array('value' => '45', 'label' => '45'),
      array('value' => '50', 'label' => '50'),
      array('value' => '55', 'label' => '55')
    ),
    'ampm' => array(
      array('value' => 'am', 'label' => 'am'),
      array('value' => 'pm', 'label' => 'pm')
    )
  );

?>